import { useState } from 'react'
import { FileText, Download, Printer, FileSpreadsheet, BarChart3, Users, Calendar, Wallet, Briefcase, FileCheck, LifeBuoy } from 'lucide-react'
import { PageHeader } from '@/components/PageHeader'
import { ChartCard } from '@/components/ChartCard'
import { generateGenericReportPDF } from '@/lib/pdfEngine'
import toast from 'react-hot-toast'

const reportTypes = [
  { id: 'employees', label: 'Employee Report', icon: Users, desc: 'Complete employee directory with details, departments, and status', accent: 'violet' },
  { id: 'attendance', label: 'Attendance Report', icon: Calendar, desc: 'Monthly attendance summary with present/absent/late breakdown', accent: 'cyan' },
  { id: 'salary', label: 'Salary Report', icon: Wallet, desc: 'Salary expenditure analysis by department and role', accent: 'amber' },
  { id: 'payroll', label: 'Payroll Report', icon: FileCheck, desc: 'Processed payroll with net payouts and deductions', accent: 'emerald' },
  { id: 'payslip', label: 'Payslip Report', icon: FileText, desc: 'Generated payslips with publication status', accent: 'violet' },
  { id: 'contract', label: 'Contract Report', icon: FileText, desc: 'Active and expiring contracts overview', accent: 'blue' },
  { id: 'leave', label: 'Leave Report', icon: Calendar, desc: 'Leave requests and approvals summary', accent: 'rose' },
  { id: 'performance', label: 'Performance Report', icon: BarChart3, desc: 'Employee performance scores and reviews', accent: 'indigo' },
  { id: 'client', label: 'Client Report', icon: Briefcase, desc: 'Active clients and service delivery status', accent: 'emerald' },
  { id: 'corporate', label: 'Corporate Report', icon: Briefcase, desc: 'Corporate accounts and contract values', accent: 'indigo' },
  { id: 'ticket', label: 'Ticket Report', icon: LifeBuoy, desc: 'Support ticket metrics and resolution times', accent: 'rose' },
  { id: 'it_asset', label: 'IT Asset Report', icon: BarChart3, desc: 'Asset inventory and assignment status', accent: 'amber' },
  { id: 'bi', label: 'BI Report', icon: BarChart3, desc: 'Comprehensive business intelligence summary', accent: 'violet' },
]

export function ReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null)

  const handleGenerate = (report: typeof reportTypes[0]) => {
    setGenerating(report.id)
    setTimeout(() => {
      const doc = generateGenericReportPDF({
        title: report.label,
        referenceNo: `MYN-RPT-${Date.now().toString().slice(-8)}`,
        meta: [
          { label: 'Report Type', value: report.label },
          { label: 'Period', value: 'August 2025' },
          { label: 'Generated By', value: 'Dashboard User' },
          { label: 'Total Records', value: '248' },
        ],
        summary: `This ${report.label.toLowerCase()} provides a comprehensive overview of ${report.desc.toLowerCase()}. The report covers all active records in the system for the specified period and includes detailed breakdowns by relevant dimensions.`,
        table: {
          head: ['ID', 'Name', 'Department', 'Status', 'Date'],
          body: [
            ['001', 'Ali Raza', 'Customer Support', 'Active', '2025-08-15'],
            ['002', 'Sara Khan', 'HR', 'Active', '2025-08-15'],
            ['003', 'Bilal Ahmed', 'Customer Support', 'Active', '2025-08-15'],
            ['004', 'Ayesha Malik', 'Customer Support', 'Active', '2025-08-15'],
            ['005', 'Usman Tariq', 'IT', 'Active', '2025-08-15'],
          ],
        },
        notes: 'This report was generated automatically by the MYNE7X BPO platform. All data is sourced from the live operational database.',
      })
      doc.save(`${report.label.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`)
      setGenerating(null)
      toast.success(`${report.label} generated successfully`)
    }, 800)
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports Center"
        description="Generate, download, and print professional reports"
        icon={<FileSpreadsheet className="h-5 w-5 text-brand-violet" />}
        breadcrumbs={[{ label: 'Dashboard' }, { label: 'Reports' }]}
      />

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {reportTypes.map((r) => (
          <ChartCard key={r.id} title={r.label} description={r.desc}>
            <div className="flex items-center justify-between mb-4">
              <div className={`p-3 rounded-xl bg-${r.accent}-500/15 ring-1 ring-${r.accent}-500/20`}>
                <r.icon className={`h-6 w-6 text-${r.accent}-400`} />
              </div>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => handleGenerate(r)}
                disabled={generating === r.id}
                className="btn-primary flex-1 text-xs"
              >
                {generating === r.id ? (
                  <span className="inline-block h-3 w-3 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                ) : (
                  <><Download className="h-3 w-3" /> Generate PDF</>
                )}
              </button>
              <button onClick={() => toast.success(`Printing ${r.label}`)} className="btn-secondary text-xs">
                <Printer className="h-3 w-3" />
              </button>
            </div>
          </ChartCard>
        ))}
      </div>
    </div>
  )
}
